language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $gh_token # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: master
  deployment_file: true
  on:
    branch: dev
    