language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 52b8572e56137a8d6ad94d153705d5aedf70ada2 # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master