language : node_js
node_js : -lts /*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
github - token : 8305 a77e2bfa8b4f7e0f66aa6062711ab17722b5 # a token generated on github allowing travis to push code on you repository

  keep-history: true
  on:
    branch: master
